### ISSUE TITLE
 undefined method `scan' for #<Hash:0x007fa6f04d66f8>

### ISSUE THREAD

**Issue by skatkov** [diogob/activerecord-postgres-hstore#130]
This worked for me before, now i'm updated to Rails 4 (after Rails 3) and receive this error:

```
  1) ServiceMessage should save facebook data
     Failure/Error: create(code:"#{FACEBOOK_LOGIN_ANSWER}_#{SecureRandom.uuid}", data: data)
     
     NoMethodError:
       undefined method `scan' for #<Hash:0x007fa6f04d66f8>
     # /Users/sk/.rvm/gems/ruby-2.1.6/gems/pg-hstore-1.2.0/lib/pg_hstore.rb:24:in `load'
     # /Users/sk/.rvm/gems/ruby-2.1.6/gems/activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/coder.rb:33:in `from_hstore'
     # /Users/sk/.rvm/gems/ruby-2.1.6/gems/activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/coder.rb:23:in `load'
     # /Users/sk/.rvm/gems/ruby-2.1.6/gems/activerecord-postgres-hstore-0.7.7/lib/activerecord-postgres-hstore/coder.rb:7:in `load'

```

For this code:

```
class ServiceMessage < ActiveRecord::Base
  serialize :data, ActiveRecord::Coders::Hstore
  attr_accessible :code, :data
  self.primary_key = 'code'

  FACEBOOK_LOGIN_ANSWER = 'FBLA'.freeze

  def self.fb_answer(data)
    require 'securerandom'
    create(code:"#{FACEBOOK_LOGIN_ANSWER}_#{SecureRandom.uuid}", data: data)
  end
end
```

With this test:
```
require 'spec_helper'

describe ServiceMessage do
  let(:auth_hash) {
    {
        :provider => 'facebook',
        :uid => '1234567',
        :info => {
            :email => 'joe@bloggs.com',
            :name => 'Joe Bloggs',
            :first_name => 'Joe',
            :last_name => 'Bloggs',
            :image => 'http://graph.facebook.com/1234567/picture?type=square',
            :urls => { :Facebook => 'http://www.facebook.com/jbloggs' },
            :location => 'Palo Alto, California',
            :verified => true
        },
        :credentials => {
            :token => 'ABCDEF...', # OAuth 2.0 access_token, which you may wish to store
            :expires_at => 1321747205, # when the access token expires (it always will)
            :expires => true # this will always be true
        },
        :extra => {
            :raw_info => {
                :id => '1234567',
                :name => 'Joe Bloggs',
                :first_name => 'Joe',
                :last_name => 'Bloggs',
                :link => 'http://www.facebook.com/jbloggs',
                :username => 'jbloggs',
                :location => { :id => '123456789', :name => 'Palo Alto, California' },
                :gender => 'male',
                :email => 'joe@bloggs.com',
                :timezone => -8,
                :locale => 'en_US',
                :verified => true,
                :updated_time => '2011-11-11T06:21:03+0000'
            }
        }
    }
  }

  it 'should save facebook data' do
    expect(ServiceMessage.fb_answer(auth_hash).id).to match(/FBLA_[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}/)
  end
end
```

    activerecord-postgres-hstore (0.7.7)
      activerecord (>= 3.1)
      pg-hstore (>= 1.1.5)
      rake

ruby 2.1.6

**Comment by skatkov** [comment]
Oh, nevermind, i just removed 
serialize :data, ActiveRecord::Coders::Hstore

and everything works :)
