### ISSUE TITLE
undefined method simplified_type for class ActiveRecord::ConnectionAdapters::PostgreSQLColumn

### ISSUE THREAD

**Issue by sawantprasann** [diogob/activerecord-postgres-hstore#133]
I am using rails 5 and ruby 2.3.1. when i installed activerecord-postgres-hstore  gem i got following error.

/activesupport-5.0.0.1/lib/active_support/core_ext/module/aliasing.rb:37:in `alias_method': undefined method `simplified_type' for class `ActiveRecord::ConnectionAdapters::PostgreSQLColumn' (NameError)
	from /activesupport-5.0.0.1/lib/active_support/core_ext/module/aliasing.rb:37:in `alias_method_chain'.

**Comment by diogob** [comment]
@sawantprasann you should be able to use hstore [without this gem](https://github.com/diogob/activerecord-postgres-hstore#note-about-rails-4) since Rails 4.
Is there any particular reason to use it instead of the hstore built-in support?

**Comment by Urielable** [comment]
I have the same issue: 

* Rails: 5.0.0.1
* ruby: 2.3.1
* pg: 9.6.0

The issue appears when run:

```bash
$ rails g hstore:setup
```

Output: 
```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. 
(called from alias_method_chain at /home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/core_ext/module/aliasing.rb:27)
2016-10-18 21:23:37 +0000: Read error: #<NameError: undefined method `simplified_type' for class `ActiveRecord::ConnectionAdapters::PostgreSQLColumn'>
```

**Comment by diogob** [comment]
@Urielable @sawantprasann in Rails 5 you should not need this gem, since hstore is supported out of the box. Any particular reason to keep using it?

**Comment by hlascelles** [comment]
One reason we would like to use it is that the default return value for a null DB field is not `nil` but `{}`. We didn't like adding nil check access everywhere.

We *could* change the DB column default to `''` I guess, but we have some very large tables which will involve some very long running migrations.

**Comment by copremesis** [comment]
yup removing the gem `activerecord-postgres-hstore` did the trick 


rails 4.2.8/ruby 2.4.2
