### ISSUE TITLE
hstore:step error with rails 5.0.0.1

### ISSUE THREAD

**Issue by aashish** [diogob/activerecord-postgres-hstore#134]
rails g hstore:setup
/home/chittimilla/.rvm/gems/ruby-2.3.1@oms/gems/activesupport-5.0.0.1/lib/active_support/core_ext/module/aliasing.rb:37:in `alias_method': undefined method `simplified_type' for class `ActiveRecord::ConnectionAdapters::PostgreSQLColumn' (NameError)
	from /home/chittimilla/.rvm/gems/ruby-2.3.1@oms/gems/activesupport-5.0.0.1/lib/active_support/core_ext/module/aliasing.rb:37:in `alias_method_chain'
	from /home/chittimilla/.rvm/gems/ruby-2.3.1@oms/gems/activerecord-postgres-hstore-0.7.8/lib/activerecord-postgres-hstore/activerecord.rb:80:in `<class:PostgreSQLColumn>'
	from /home/chittimilla/.rvm/gems/ruby-2.3.1@oms/gems/activerecord-postgres-hstore-0.7.8/lib/activerecord-postgres-hstore/activerecord.rb:74:in `<module:ConnectionAdapters>'
	from /home/chittimilla/.rvm/gems/ruby-2.3.1@oms/gems/activerecord-postgres-hstore-0.7.8/lib/activerecord-postgres-hstore/activerecord.rb:70:in `<module:ActiveRecord>'
	from /home/chittimilla/.rvm/gems/ruby-

**Comment by aashish** [comment]
resolved this gem on rails 5
add migration
    enable_extension "hstore"   
    add_column :orders, :data, :hstore, default: {}, null: false
